"""Generate the matched, UIPC-friendly screw-light-bulb surface assets.

Run this script before ``scripts/convert.py``.  The male ridge and female
groove use the same helical coordinate, while the socket groove remains open
at the top surface so the thread can actually advance into the socket.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import numpy as np
import trimesh


ASSET_DIR = Path(__file__).resolve().parents[1] / "assets/objects/task_assets/screw_bulb"
SIDES = 96
PITCH = 0.010
THREAD_START_Z = 0.008
THREAD_END_Z = 0.034
THREAD_CORE_RADIUS = 0.0115
THREAD_MAJOR_RADIUS = 0.0140
SOCKET_MINOR_RADIUS = 0.0132
SOCKET_GROOVE_RADIUS = 0.0163
SOCKET_HEIGHT = 0.055
INITIAL_INSERTION = 0.006

ANGLES = np.arange(SIDES, dtype=np.float64) * (2.0 * np.pi / SIDES)


class MeshBuilder:
    def __init__(self) -> None:
        self.vertices: list[tuple[float, float, float]] = []
        self.faces: list[tuple[int, int, int]] = []
        self.face_materials: list[str] = []

    def add_ring(self, z: float, radii: float | np.ndarray) -> np.ndarray:
        radii = np.broadcast_to(np.asarray(radii, dtype=np.float64), (SIDES,))
        start = len(self.vertices)
        self.vertices.extend(
            (float(r * np.cos(a)), float(r * np.sin(a)), float(z))
            for r, a in zip(radii, ANGLES)
        )
        return np.arange(start, start + SIDES, dtype=np.int64)

    def add_center(self, z: float) -> int:
        index = len(self.vertices)
        self.vertices.append((0.0, 0.0, float(z)))
        return index

    def add_face(self, a: int, b: int, c: int, material: str) -> None:
        self.faces.append((int(a), int(b), int(c)))
        self.face_materials.append(material)

    def connect_outer(self, low: np.ndarray, high: np.ndarray, material: str) -> None:
        for side in range(SIDES):
            nxt = (side + 1) % SIDES
            self.add_face(low[side], low[nxt], high[nxt], material)
            self.add_face(low[side], high[nxt], high[side], material)

    def connect_inner(self, high: np.ndarray, low: np.ndarray, material: str) -> None:
        for side in range(SIDES):
            nxt = (side + 1) % SIDES
            self.add_face(high[side], high[nxt], low[nxt], material)
            self.add_face(high[side], low[nxt], low[side], material)

    def cap_bottom(self, ring: np.ndarray, center: int, material: str) -> None:
        for side in range(SIDES):
            nxt = (side + 1) % SIDES
            self.add_face(center, ring[nxt], ring[side], material)

    def cap_top(self, ring: np.ndarray, center: int, material: str) -> None:
        for side in range(SIDES):
            nxt = (side + 1) % SIDES
            self.add_face(center, ring[side], ring[nxt], material)

    def add_top_annulus(
        self,
        outer: np.ndarray,
        inner: np.ndarray,
        material: str,
    ) -> None:
        for side in range(SIDES):
            nxt = (side + 1) % SIDES
            self.add_face(outer[side], outer[nxt], inner[nxt], material)
            self.add_face(outer[side], inner[nxt], inner[side], material)

    def validate(self, name: str) -> None:
        mesh = trimesh.Trimesh(
            vertices=np.asarray(self.vertices),
            faces=np.asarray(self.faces),
            process=False,
        )
        if not mesh.is_watertight:
            raise RuntimeError(f"{name} is not watertight")
        if not mesh.is_winding_consistent:
            raise RuntimeError(f"{name} has inconsistent face winding")
        if mesh.volume <= 0.0:
            raise RuntimeError(f"{name} has inward-facing triangles")

    def write_obj(self, path: Path, object_name: str, mtl_name: str) -> None:
        lines = [
            f"# Generated by {Path(__file__).name}",
            "# Units: meters; Z up; origin at bottom-face center",
            f"mtllib {mtl_name}",
            f"o {object_name}",
            "",
        ]
        lines.extend(f"v {x:.9f} {y:.9f} {z:.9f}" for x, y, z in self.vertices)
        lines.append("")
        grouped: dict[str, list[tuple[int, int, int]]] = defaultdict(list)
        for face, material in zip(self.faces, self.face_materials):
            grouped[material].append(face)
        for material, faces in grouped.items():
            lines.append(f"usemtl {material}")
            lines.extend(f"f {a + 1} {b + 1} {c + 1}" for a, b, c in faces)
            lines.append("")
        path.write_text("\n".join(lines), encoding="ascii")


def wrapped_thread_profile(angle: np.ndarray) -> np.ndarray:
    wrapped = np.arctan2(np.sin(angle), np.cos(angle))
    half_width = np.deg2rad(58.0)
    return np.clip(1.0 - np.abs(wrapped) / half_width, 0.0, 1.0)


def bulb_thread_radii(z: float) -> np.ndarray:
    phase = ANGLES - (2.0 * np.pi * z / PITCH)
    profile = wrapped_thread_profile(phase)
    lead = np.clip((z - THREAD_START_Z) / 0.0015, 0.0, 1.0)
    runout = np.clip((THREAD_END_Z - z) / 0.0015, 0.0, 1.0)
    envelope = min(float(lead), float(runout))
    return THREAD_CORE_RADIUS + (
        THREAD_MAJOR_RADIUS - THREAD_CORE_RADIUS
    ) * profile * envelope


def socket_thread_radii(z: float) -> np.ndarray:
    initial_bottom_offset = SOCKET_HEIGHT - INITIAL_INSERTION
    socket_phase = 2.0 * np.pi * initial_bottom_offset / PITCH
    phase = ANGLES - (2.0 * np.pi * z / PITCH) + socket_phase
    profile = wrapped_thread_profile(phase)
    return SOCKET_MINOR_RADIUS + (
        SOCKET_GROOVE_RADIUS - SOCKET_MINOR_RADIUS
    ) * profile


def build_bulb() -> MeshBuilder:
    mesh = MeshBuilder()
    rings: list[tuple[float, np.ndarray, str]] = []

    for z in (0.0, 0.004, THREAD_START_Z):
        rings.append((z, mesh.add_ring(z, THREAD_CORE_RADIUS), "bulb_contact_metal"))
    for z in np.linspace(THREAD_START_Z + 0.00025, THREAD_END_Z, 104):
        rings.append((float(z), mesh.add_ring(float(z), bulb_thread_radii(float(z))), "bulb_thread_brass"))

    upper_profile = (
        (0.036, 0.0120, "bulb_neck_metal"),
        (0.041, 0.0140, "bulb_neck_metal"),
        (0.046, 0.0165, "bulb_glass_warm"),
        (0.050, 0.0180, "bulb_glass_warm"),
        (0.055, 0.0192, "bulb_glass_warm"),
        (0.060, 0.0200, "bulb_glass_warm"),
        (0.065, 0.0199, "bulb_glass_warm"),
        (0.070, 0.0192, "bulb_glass_warm"),
        (0.075, 0.0178, "bulb_glass_warm"),
        (0.080, 0.0150, "bulb_glass_warm"),
        (0.084, 0.0100, "bulb_glass_warm"),
        (0.086, 0.0050, "bulb_glass_warm"),
    )
    for z, radius, material in upper_profile:
        rings.append((z, mesh.add_ring(z, radius), material))

    for (_, low, low_material), (_, high, high_material) in zip(rings, rings[1:]):
        material = high_material if high_material != low_material else low_material
        mesh.connect_outer(low, high, material)
    mesh.cap_bottom(rings[0][1], mesh.add_center(0.0), "bulb_contact_metal")
    mesh.cap_top(rings[-1][1], mesh.add_center(0.088), "bulb_glass_warm")
    return mesh


def build_socket() -> MeshBuilder:
    mesh = MeshBuilder()
    outer_profile = (
        (0.000, 0.0400),
        (0.006, 0.0400),
        (0.011, 0.0360),
        (0.045, 0.0360),
        (0.051, 0.0400),
        (SOCKET_HEIGHT, 0.0400),
    )
    outer = [(z, mesh.add_ring(z, radius)) for z, radius in outer_profile]
    for (_, low), (_, high) in zip(outer, outer[1:]):
        mesh.connect_outer(low, high, "socket_ceramic")
    mesh.cap_bottom(outer[0][1], mesh.add_center(0.0), "socket_ceramic")

    inner = [
        (float(z), mesh.add_ring(float(z), socket_thread_radii(float(z))))
        for z in np.linspace(SOCKET_HEIGHT, 0.012, 121)
    ]
    mesh.add_top_annulus(outer[-1][1], inner[0][1], "socket_rim_brass")
    for (_, high), (_, low) in zip(inner, inner[1:]):
        mesh.connect_inner(high, low, "socket_thread_brass")
    mesh.cap_top(inner[-1][1], mesh.add_center(0.012), "socket_thread_brass")
    return mesh


def write_materials() -> None:
    bulb_mtl = """# Generated light-bulb materials
newmtl bulb_glass_warm
Ka 0.16 0.13 0.07
Kd 0.92 0.76 0.30
Ks 0.38 0.34 0.20
Ns 70
illum 2

newmtl bulb_thread_brass
Ka 0.12 0.07 0.02
Kd 0.58 0.34 0.08
Ks 0.72 0.55 0.24
Ns 95
illum 2

newmtl bulb_neck_metal
Ka 0.06 0.07 0.07
Kd 0.25 0.28 0.29
Ks 0.65 0.68 0.68
Ns 110
illum 2

newmtl bulb_contact_metal
Ka 0.02 0.02 0.02
Kd 0.08 0.09 0.09
Ks 0.35 0.38 0.38
Ns 80
illum 2
"""
    socket_mtl = """# Generated lamp-socket materials
newmtl socket_ceramic
Ka 0.10 0.11 0.12
Kd 0.72 0.76 0.78
Ks 0.30 0.32 0.33
Ns 45
illum 2

newmtl socket_rim_brass
Ka 0.13 0.08 0.02
Kd 0.62 0.38 0.09
Ks 0.72 0.55 0.22
Ns 90
illum 2

newmtl socket_thread_brass
Ka 0.06 0.04 0.01
Kd 0.30 0.20 0.06
Ks 0.50 0.38 0.15
Ns 70
illum 2
"""
    (ASSET_DIR / "light_bulb_two_turn_thread.mtl").write_text(bulb_mtl, encoding="ascii")
    (ASSET_DIR / "lamp_socket_two_turn_thread.mtl").write_text(socket_mtl, encoding="ascii")


def main() -> None:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    bulb = build_bulb()
    socket = build_socket()
    bulb.validate("light bulb")
    socket.validate("lamp socket")
    write_materials()
    bulb.write_obj(
        ASSET_DIR / "light_bulb_two_turn_thread.obj",
        "light_bulb_two_turn_thread",
        "light_bulb_two_turn_thread.mtl",
    )
    socket.write_obj(
        ASSET_DIR / "lamp_socket_two_turn_thread.obj",
        "lamp_socket_two_turn_internal_thread",
        "lamp_socket_two_turn_thread.mtl",
    )
    print(
        f"Generated bulb ({len(bulb.vertices)} vertices, {len(bulb.faces)} faces) "
        f"and socket ({len(socket.vertices)} vertices, {len(socket.faces)} faces)."
    )


if __name__ == "__main__":
    main()
